### ISSUE TITLE
How does one deploy this with ansible?

### ISSUE THREAD

**Issue by uhlhosting** [stuvusIT/mattermost-hubot#3]
Is this for remote deployment? Or for local ansible deployment, can you provide some startup steps? It is not clear if the recipe to be used remotely or local on ubuntu.

**Comment by Scriptkiddi** [comment]
Hey I dont understand where you draw the line between remote and local deployment. I will add the startup steps in a couple minutes

**Comment by Scriptkiddi** [comment]
Actually I will just do it here:
You clone the role your_inventory_dir/roles add a playbook with the content of the example playbook from the readme and define a host where you want to deploy the role to, then you run `ansible-playbook playbook.yml` 
Let me know if that clarifies things
